name: Create Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - name: Create tag
      run: |
        TAG_NAME=v$(node -p "require('./package.json').version")
        echo $TAG_NAME tag
        git tag $TAG_NAME
        git push origin $TAG_NAME
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: |
          $TAG_NAME
          echo $TAG_NAME release
        release_name: Release $TAG_NAME
        body: |
          This is the release for version ${{ github.ref_type }}.
          It includes the following changes:
          - ...
          - ...
        draft: false
        prerelease: false