name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract version from package.json
      run: PACKAGE_VERSION=$npm pkg get version
    - name: Print version
      run: echo "Version $PACKAGE_VERSION"