name: Create Release

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract version from package.json
      run: |
        version=$(cat package.json | jq -r '.version')
    - name: Add tag with version
      run: git tag $version