on: push
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        run: echo "PACKAGE_VERSION=$(cat ${GITHUB_WORKSPACE}/VERSION)" >> $GITHUB_ENV
        with:
          tag_name: v ${{ env.PACKAGE_VERSION }}
          release_name: Release v ${{ env.PACKAGE_VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false