name: Create Release

on:
  push:
    branches:
      - main
    paths:
    - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - name: Create tag
      run: |
        TAG_NAME=v$(node -p "require('./package.json').version")
        git tag $TAG_NAME
        git push origin $TAG_NAME