name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract version from package.json
      run: version=$(cat ../../package.json | jq -r '.version')
    - name: Print version
      run: echo "Version $version"