name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get path to package.json
      run: path=$(git ls-tree HEAD package.json | awk '{print $4}')
    - name: Print path
      run: echo "Path -> $path"
    - name: Extract version from package.json
      run: version=$(cat $path | jq -r '.version')
    - name: Print version
      run: echo "Version -> $version"
    - name: Add tag with version
      run: git tag $version
    - name: Push tag
      run: git push origin $version